branches:
  only:
  - master
  - qa

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  BUILD_ENV
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    export BUILD_ENV=build_dev
    fi
  - if [ "$TRAVIS_BRANCH" == "uat" ]; then
    export BUILD_ENV=build_uat
    fi
  - docker build --build-arg BUILD_ENV -f docker/Dockerfile --no-cache -t ithriv/ithriv_web:"$TRAVIS_BRANCH" . || exit 1 ;
  - docker push ithriv/ithriv_web:"$TRAVIS_BRANCH" || exit 1 ;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag ithriv/ithriv_web:"$TRAVIS_BRANCH" ithriv/ithriv_web:latest || exit 1 ;
    docker push ithriv/ithriv_web:latest || exit 1 ;
    fi
  - aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/ithriv-updates' --message-body ithriv/ithriv_web:$TRAVIS_BRANCH || exit 1;


notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - rkc7h@virginia.edu