version: '3.5'
networks:
  ithriv_network:
    external: true
services:
  ithriv_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ithriv_web
    ports:
      - 4200:4200
    networks:
      - ithriv_network

